# File: .github/workflows/workflow.yml

on: [push]
defaults:
  run:
    working-directory: project-front
jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install dependencies
        run: npm install 
      - name: Build
        run: npm run-script build 
      - name: Install dependencies
        run: ls
      - uses: azure/login@v1
        with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Install dependencies
        run: az account set -s ${{ secrets.AZURE_SUB }}
      - name: Install dependencies
        run: az account list
      - name: Upload to blob storage
        uses: azure/CLI@v1
        with:
          azcliversion: 2.0.72
          inlineScript: |
              az storage blob upload-batch --account-name alanfachim -d '$web' -s ./project-front/dist/my-first-app
      - name: Purge CDN endpoint
        uses: azure/CLI@v1
        with:
          azcliversion: 2.0.72
          inlineScript: |
            az cdn endpoint purge --content-paths  "/*" --profile-name "website" --name "drpins" --resource-group "alanbrasilbr"
      # Azure logout 
      - name: logout
        run: |
              az logout

           
